ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Pea Beetle"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Look at it wander around."
ENT.Instructions 	= "Click to spawn it."
ENT.Category		= "E.Y.E Divine Cybermancy"