ENT.Base 			= "npc_vj_eye_forma"
ENT.Type 			= "ai"
ENT.PrintName 		= "Evil Deer"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "E.Y.E Divine Cybermancy"